version: '2'

services:

  orderer.microgrid.org:
    container_name: orderer.microgrid.org
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/microgrid.org/orderers/orderer.microgrid.org/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/microgrid.org/orderers/orderer.microgrid.org/tls/:/var/hyperledger/orderer/tls
    - orderer.microgrid.org:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.house01.microgrid.org:
    container_name: peer0.house01.microgrid.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.house01.microgrid.org
      - CORE_PEER_ADDRESS=peer0.house01.microgrid.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.house01.microgrid.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.house01.microgrid.org:7051
      - CORE_PEER_LOCALMSPID=House01tMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/house01.microgrid.org/peers/peer0.house01.microgrid.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/house01.microgrid.org/peers/peer0.house01.microgrid.org/tls:/etc/hyperledger/fabric/tls
        - peer0.house01.microgrid.org:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.house01.microgrid.org:
    container_name: peer1.house01.microgrid.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.house01.microgrid.org
      - CORE_PEER_ADDRESS=peer1.house01.microgrid.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.house01.microgrid.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.house01.microgrid.org:7051
      - CORE_PEER_LOCALMSPID=House01MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/house01.microgrid.org/peers/peer1.house01.microgrid.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/house01.microgrid.org/peers/peer1.house01.microgrid.org/tls:/etc/hyperledger/fabric/tls
        - peer1.house01.microgrid.org:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.house02.microgrid.org:
    container_name: peer0.house02.microgrid.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.house02.microgrid.org
      - CORE_PEER_ADDRESS=peer0.house02.microgrid.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.house02.microgrid.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.house02.microgrid.org:7051
      - CORE_PEER_LOCALMSPID=House02MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/house02.microgrid.org/peers/peer0.house02.microgrid.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/house02.microgrid.org/peers/peer0.house02.microgrid.org/tls:/etc/hyperledger/fabric/tls
        - peer0.house02.microgrid.org:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.house02.microgrid.org:
    container_name: peer1.house02.microgrid.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.house02.microgrid.org
      - CORE_PEER_ADDRESS=peer1.house02.microgrid.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.house02.microgrid.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.house02.microgrid.org:7051
      - CORE_PEER_LOCALMSPID=House02MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/house02.microgrid.org/peers/peer1.house02.microgrid.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/house02.microgrid.org/peers/peer1.house02.microgrid.org/tls:/etc/hyperledger/fabric/tls
        - peer1.house02.microgrid.org:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053

  peer0.house03.microgrid.org:
    container_name: peer0.house03.microgrid.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.house03.microgrid.org
      - CORE_PEER_ADDRESS=peer0.house03.microgrid.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.house03.microgrid.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.house03.microgrid.org:7051
      - CORE_PEER_LOCALMSPID=House03MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/house03.microgrid.org/peers/peer0.house03.microgrid.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/house03.microgrid.org/peers/peer0.house03.microgrid.org/tls:/etc/hyperledger/fabric/tls
        - peer0.house03.microgrid.org:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053

  peer1.house03.microgrid.org:
    container_name: peer1.house03.microgrid.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.house03.microgrid.org
      - CORE_PEER_ADDRESS=peer1.house03.microgrid.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.house03.microgrid.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.house03.microgrid.org:7051
      - CORE_PEER_LOCALMSPID=House03MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/house03.microgrid.org/peers/peer1.house03.microgrid.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/house03.microgrid.org/peers/peer1.house03.microgrid.org/tls:/etc/hyperledger/fabric/tls
        - peer1.house03.microgrid.org:/var/hyperledger/production
    ports:
      - 12051:7051
      - 12053:7053

  peer0.house04.microgrid.org:
    container_name: peer0.house04.microgrid.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.house04.microgrid.org
      - CORE_PEER_ADDRESS=peer0.house04.microgrid.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.house04.microgrid.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.house04.microgrid.org:7051
      - CORE_PEER_LOCALMSPID=House04MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/house04.microgrid.org/peers/peer0.house04.microgrid.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/house04.microgrid.org/peers/peer0.house04.microgrid.org/tls:/etc/hyperledger/fabric/tls
        - peer0.house04.microgrid.org:/var/hyperledger/production
    ports:
      - 13051:7051
      - 13053:7053

  peer1.house04.microgrid.org:
    container_name: peer1.house04.microgrid.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.house04.microgrid.org
      - CORE_PEER_ADDRESS=peer1.house04.microgrid.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.house04.microgrid.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.house04.microgrid.org:7051
      - CORE_PEER_LOCALMSPID=House04MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/house04.microgrid.org/peers/peer1.house04.microgrid.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/house04.microgrid.org/peers/peer1.house04.microgrid.org/tls:/etc/hyperledger/fabric/tls
        - peer1.house04.microgrid.org:/var/hyperledger/production
    ports:
      - 14051:7051
      - 14053:7053

  peer0.house05.microgrid.org:
    container_name: peer0.house05.microgrid.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.house05.microgrid.org
      - CORE_PEER_ADDRESS=peer0.house05.microgrid.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.house05.microgrid.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.house05.microgrid.org:7051
      - CORE_PEER_LOCALMSPID=House05MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/house05.microgrid.org/peers/peer0.house05.microgrid.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/house05.microgrid.org/peers/peer0.house05.microgrid.org/tls:/etc/hyperledger/fabric/tls
        - peer0.house05.microgrid.org:/var/hyperledger/production
    ports:
      - 15051:7051
      - 15053:7053

  peer1.house05.microgrid.org:
    container_name: peer1.house05.microgrid.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.house05.microgrid.org
      - CORE_PEER_ADDRESS=peer1.house05.microgrid.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.house05.microgrid.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.house05.microgrid.org:7051
      - CORE_PEER_LOCALMSPID=House05MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/house05.microgrid.org/peers/peer1.house05.microgrid.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/house05.microgrid.org/peers/peer1.house05.microgrid.org/tls:/etc/hyperledger/fabric/tls
        - peer1.house05.microgrid.org:/var/hyperledger/production
    ports:
      - 16051:7051
      - 16053:7053

  peer0.house06.microgrid.org:
    container_name: peer0.house06.microgrid.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.house06.microgrid.org
      - CORE_PEER_ADDRESS=peer0.house06.microgrid.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.house06.microgrid.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.house06.microgrid.org:7051
      - CORE_PEER_LOCALMSPID=House06MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/house06.microgrid.org/peers/peer0.house06.microgrid.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/house06.microgrid.org/peers/peer0.house06.microgrid.org/tls:/etc/hyperledger/fabric/tls
        - peer0.house06.microgrid.org:/var/hyperledger/production
    ports:
      - 17051:7051
      - 17053:7053

  peer1.house06.microgrid.org:
    container_name: peer1.house06.microgrid.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.house06.microgrid.org
      - CORE_PEER_ADDRESS=peer1.house06.microgrid.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.house06.microgrid.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.house06.microgrid.org:7051
      - CORE_PEER_LOCALMSPID=House06MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=        
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/house06.microgrid.org/peers/peer1.house06.microgrid.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/house06.microgrid.org/peers/peer1.house06.microgrid.org/tls:/etc/hyperledger/fabric/tls
        - peer1.house06.microgrid.org:/var/hyperledger/production
    ports:
      - 18051:7051
      - 18053:7053
